# Generated by Django 3.2.9 on 2021-11-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('numero_telefono', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
                'managed': True,
            },
        ),
    ]
