# Generated by Django 3.2.9 on 2021-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0002_alter_mensajes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
