# Generated by Django 4.0 on 2022-01-15 04:25

from django.db import migrations, models
import mensajes.models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0003_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensajes',
            options={'managed': True, 'verbose_name': 'mensaje', 'verbose_name_plural': 'mensajes'},
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='mensaje',
            field=models.TextField(validators=[mensajes.models.Mensajes.validate_message]),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='nombre_contacto',
            field=models.CharField(max_length=100, validators=[mensajes.models.Mensajes.validate_name]),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='numero_telefono',
            field=models.PositiveBigIntegerField(validators=[mensajes.models.Mensajes.validate_length]),
        ),
        migrations.AlterModelTable(
            name='mensajes',
            table='mensaje',
        ),
    ]
